import type { AigcCategory } from "../types";

const MOCK_DATA: AigcCategory[] = [
  {
    id: "image",
    name: "图片生成",
    icon: "🎨",
    platforms: [
      {
        id: "midjourney",
        name: "Midjourney",
        description: "高质量概念图、角色氛围图、场景探索与宣传视觉。",
        category: "image",
        url: "https://www.midjourney.com/",
        supported_types: ["概念图", "角色", "场景"],
        status: "online",
      },
      {
        id: "chatgpt_images",
        name: "ChatGPT Images",
        description: "通用图像生成与编辑，适合快速方案草图和多轮修改。",
        category: "image",
        url: "https://chatgpt.com/",
        supported_types: ["图像生成", "编辑", "多轮"],
        status: "online",
      },
      {
        id: "adobe_firefly",
        name: "Adobe Firefly",
        description: "偏商业设计与素材生产，适合宣传图、字体效果和品牌视觉。",
        category: "image",
        url: "https://firefly.adobe.com/",
        supported_types: ["商业设计", "素材", "文字效果"],
        status: "online",
      },
      {
        id: "leonardo",
        name: "Leonardo.Ai",
        description: "面向游戏资产与美术创作的图像平台，适合角色、道具和风格探索。",
        category: "image",
        url: "https://leonardo.ai/",
        supported_types: ["游戏美术", "资产", "风格"],
        status: "online",
      },
      {
        id: "ideogram",
        name: "Ideogram",
        description: "擅长带文字的海报、Logo、封面和视觉排版。",
        category: "image",
        url: "https://ideogram.ai/",
        supported_types: ["海报", "Logo", "文字"],
        status: "online",
      },
      {
        id: "recraft",
        name: "Recraft",
        description: "矢量、图标、品牌图形和可控风格资产生成。",
        category: "image",
        url: "https://www.recraft.ai/",
        supported_types: ["矢量", "图标", "品牌"],
        status: "online",
      },
      {
        id: "krea",
        name: "Krea",
        description: "实时视觉探索、图像增强和风格参考生成。",
        category: "image",
        url: "https://www.krea.ai/",
        supported_types: ["实时生成", "增强", "参考"],
        status: "online",
      },
      {
        id: "freepik",
        name: "Freepik AI",
        description: "素材站式 AI 入口，适合快速找图、改图和生成商用素材。",
        category: "image",
        url: "https://www.freepik.com/ai",
        supported_types: ["素材", "商用", "模板"],
        status: "online",
      },
      {
        id: "liblib",
        name: "LiblibAI",
        description: "中文生态常用的图像模型与工作流平台，适合模型社区和 LoRA 资产。",
        category: "image",
        url: "https://www.liblib.art/",
        supported_types: ["中文生态", "模型", "工作流"],
        status: "online",
        region: "china",
      },
      {
        id: "jimeng",
        name: "即梦 AI",
        description: "中文图片与视频创作入口，适合短视频视觉、角色图和场景草图。",
        category: "image",
        url: "https://jimeng.jianying.com/",
        supported_types: ["中文", "图片", "视频"],
        status: "online",
        region: "china",
      },
    ],
  },
  {
    id: "video",
    name: "视频生成",
    icon: "🎬",
    platforms: [
      {
        id: "runway",
        name: "Runway",
        description: "主流 AI 视频创作平台，适合镜头测试、宣传片和动态图参考。",
        category: "video",
        url: "https://runwayml.com/",
        supported_types: ["文生视频", "图生视频", "编辑"],
        status: "online",
      },
      {
        id: "kling",
        name: "Kling AI / 可灵",
        description: "快手系视频生成平台，适合中文语境、图生视频和动态镜头。",
        category: "video",
        url: "https://kling.ai/",
        supported_types: ["视频", "图生视频", "中文"],
        status: "online",
        region: "china",
      },
      {
        id: "luma",
        name: "Luma Dream Machine",
        description: "视频生成与镜头运动探索，适合概念短片和氛围验证。",
        category: "video",
        url: "https://lumalabs.ai/dream-machine",
        supported_types: ["视频", "镜头", "氛围"],
        status: "online",
      },
      {
        id: "pika",
        name: "Pika",
        description: "轻量视频生成与特效入口，适合快速做可传播片段。",
        category: "video",
        url: "https://pika.art/",
        supported_types: ["视频", "特效", "短片"],
        status: "online",
      },
      {
        id: "hailuo",
        name: "Hailuo AI / 海螺",
        description: "MiniMax 系视频创作入口，适合中文短片和角色片段生成。",
        category: "video",
        url: "https://hailuoai.video/",
        supported_types: ["视频", "中文", "短片"],
        status: "online",
        region: "china",
      },
      {
        id: "vidu",
        name: "Vidu",
        description: "国内常用视频生成平台，适合图生视频、角色一致性和短片尝试。",
        category: "video",
        url: "https://www.vidu.com/",
        supported_types: ["视频", "角色", "短片"],
        status: "online",
        region: "china",
      },
      {
        id: "pixverse",
        name: "PixVerse",
        description: "视频生成与风格化动效入口，适合快速做宣传片段。",
        category: "video",
        url: "https://pixverse.ai/",
        supported_types: ["视频", "动效", "风格"],
        status: "online",
      },
      {
        id: "higgsfield",
        name: "Higgsfield",
        description: "偏社媒与镜头效果的视频创作平台，适合动态广告和角色展示。",
        category: "video",
        url: "https://higgsfield.ai/",
        supported_types: ["镜头", "社媒", "角色"],
        status: "online",
      },
      {
        id: "sora",
        name: "Sora",
        description: "OpenAI 视频生成入口，适合高质量视频概念与镜头探索。",
        category: "video",
        url: "https://sora.chatgpt.com/",
        supported_types: ["视频", "概念", "镜头"],
        status: "online",
      },
    ],
  },
  {
    id: "audio",
    name: "声音生成",
    icon: "🎵",
    platforms: [
      {
        id: "suno",
        name: "Suno",
        description: "歌曲、主题曲、氛围音乐与带歌词音乐生成。",
        category: "audio",
        url: "https://suno.com/",
        supported_types: ["歌曲", "BGM", "歌词"],
        status: "online",
      },
      {
        id: "udio",
        name: "Udio",
        description: "音乐生成与风格化歌曲制作，适合主题曲和风格尝试。",
        category: "audio",
        url: "https://www.udio.com/",
        supported_types: ["歌曲", "风格", "音乐"],
        status: "online",
      },
      {
        id: "elevenlabs",
        name: "ElevenLabs",
        description: "高质量语音合成、角色配音、旁白和音效方向能力。",
        category: "audio",
        url: "https://elevenlabs.io/",
        supported_types: ["配音", "旁白", "音效"],
        status: "online",
      },
      {
        id: "fish_audio",
        name: "Fish Audio",
        description: "中文生态常见语音生成入口，适合角色语音与旁白尝试。",
        category: "audio",
        url: "https://fish.audio/",
        supported_types: ["语音", "中文", "角色"],
        status: "online",
      },
      {
        id: "stable_audio",
        name: "Stable Audio",
        description: "音效、音乐片段和素材化音频生成。",
        category: "audio",
        url: "https://www.stableaudio.com/",
        supported_types: ["音效", "音乐", "素材"],
        status: "online",
      },
      {
        id: "adobe_podcast",
        name: "Adobe Podcast",
        description: "语音增强、降噪和播客式音频处理，适合录音修复。",
        category: "audio",
        url: "https://podcast.adobe.com/",
        supported_types: ["增强", "降噪", "录音"],
        status: "online",
      },
    ],
  },
  {
    id: "3d",
    name: "3D 模型",
    icon: "🧊",
    platforms: [
      {
        id: "hunyuan_3d",
        name: "腾讯混元 3D",
        description: "腾讯混元 3D 资产生成入口，支持文本/图片到 3D，适合游戏资产探索。",
        category: "3d",
        url: "https://3d.hunyuan.tencent.com/",
        supported_types: ["Text-to-3D", "Image-to-3D", "GLB"],
        status: "online",
        region: "china",
      },
      {
        id: "hunyuan_3d_global",
        name: "HY 3D Studio",
        description: "混元 3D 国际版工作台入口，面向 3D 资产生成和编辑流程。",
        category: "3d",
        url: "https://3d.hunyuanglobal.com/studio",
        supported_types: ["3D Studio", "编辑", "资产"],
        status: "online",
      },
      {
        id: "meshy",
        name: "Meshy",
        description: "主流 AI 3D 资产生成平台，支持文本/图片生成模型与贴图。",
        category: "3d",
        url: "https://www.meshy.ai/",
        supported_types: ["OBJ", "FBX", "GLB"],
        status: "online",
      },
      {
        id: "tripo",
        name: "Tripo AI",
        description: "快速生成 3D 模型，适合原型资产、道具和角色草模。",
        category: "3d",
        url: "https://www.tripo3d.ai/",
        supported_types: ["3D", "角色", "道具"],
        status: "online",
      },
      {
        id: "rodin",
        name: "Rodin",
        description: "Deemos 3D 资产生成平台，适合高质量模型和 PBR 资产探索。",
        category: "3d",
        url: "https://hyper3d.ai/",
        supported_types: ["PBR", "模型", "资产"],
        status: "online",
      },
      {
        id: "luma_genie",
        name: "Luma Genie",
        description: "Luma 的 3D 生成入口，适合从文本快速试 3D 形体。",
        category: "3d",
        url: "https://lumalabs.ai/genie",
        supported_types: ["Text-to-3D", "草模", "快速"],
        status: "online",
      },
      {
        id: "spline",
        name: "Spline AI",
        description: "面向 Web 和交互原型的 3D 设计工具，适合轻量可交互场景。",
        category: "3d",
        url: "https://spline.design/ai",
        supported_types: ["Web 3D", "交互", "原型"],
        status: "online",
      },
      {
        id: "kaedim",
        name: "Kaedim",
        description: "面向游戏资产管线的 3D 生成与制作辅助平台。",
        category: "3d",
        url: "https://www.kaedim3d.com/",
        supported_types: ["游戏资产", "模型", "管线"],
        status: "online",
      },
      {
        id: "csm",
        name: "CSM",
        description: "Common Sense Machines，面向 3D 世界和资产生成。",
        category: "3d",
        url: "https://www.csm.ai/",
        supported_types: ["3D", "世界", "资产"],
        status: "online",
      },
    ],
  },
  {
    id: "ui",
    name: "原型设计",
    icon: "✨",
    platforms: [
      {
        id: "v0",
        name: "v0 by Vercel",
        description: "自然语言生成前端界面与组件代码，适合 Web 原型和管理后台。",
        category: "ui",
        url: "https://v0.dev/",
        supported_types: ["React", "Web", "组件"],
        status: "online",
      },
      {
        id: "lovable",
        name: "Lovable",
        description: "从描述生成应用原型，适合快速验证工具页、后台和产品 demo。",
        category: "ui",
        url: "https://lovable.dev/",
        supported_types: ["Web App", "原型", "代码"],
        status: "online",
      },
      {
        id: "bolt",
        name: "Bolt.new",
        description: "浏览器内生成和运行前端项目，适合快速搭建交互原型。",
        category: "ui",
        url: "https://bolt.new/",
        supported_types: ["Web", "代码", "原型"],
        status: "online",
      },
      {
        id: "framer",
        name: "Framer AI",
        description: "适合官网、落地页和可发布页面原型。",
        category: "ui",
        url: "https://www.framer.com/ai/",
        supported_types: ["Landing Page", "网站", "原型"],
        status: "online",
      },
      {
        id: "uizard",
        name: "Uizard",
        description: "产品界面、线框图和低成本 UI 原型生成。",
        category: "ui",
        url: "https://uizard.io/",
        supported_types: ["线框图", "UI", "原型"],
        status: "online",
      },
      {
        id: "motiff",
        name: "Motiff",
        description: "AI 原生 UI 设计工具，适合中文团队设计协作。",
        category: "ui",
        url: "https://www.motiff.com/",
        supported_types: ["UI", "协作", "中文"],
        status: "online",
        region: "china",
      },
      {
        id: "creatie",
        name: "Creatie",
        description: "AI 设计与 UI 工作流平台，适合设计稿生成和编辑。",
        category: "ui",
        url: "https://creatie.ai/",
        supported_types: ["设计稿", "UI", "AI"],
        status: "online",
      },
    ],
  },
  {
    id: "writing",
    name: "文字创作",
    icon: "✍️",
    platforms: [
      {
        id: "rytr",
        name: "Rytr",
        description: "轻量 AI 文案写作工具，适合快速生成短文案、说明、标题和营销文本。",
        category: "writing",
        group: "文案",
        url: "https://rytr.me/",
        supported_types: ["短文案", "标题", "营销文本"],
        status: "online",
      },
      {
        id: "sudowrite",
        name: "Sudowrite",
        description: "面向小说和创意写作的辅助工具，适合扩写、改写、角色语气和段落润色。",
        category: "writing",
        group: "文案",
        url: "https://www.sudowrite.com/",
        supported_types: ["创意写作", "扩写", "润色"],
        status: "online",
      },
      {
        id: "novelcrafter",
        name: "Novelcrafter",
        description: "带有 Codex / Lorebook 思路的长篇写作工作台，适合管理世界观、角色和章节资料。",
        category: "writing",
        group: "文案",
        url: "https://www.novelcrafter.com/",
        supported_types: ["世界观", "角色", "长文本"],
        status: "online",
      },
      {
        id: "novelai",
        name: "NovelAI",
        description: "面向叙事文本与角色风格生成的创作平台，适合尝试角色口吻和故事片段。",
        category: "writing",
        group: "文案",
        url: "https://novelai.net/",
        supported_types: ["叙事", "角色口吻", "故事片段"],
        status: "online",
      },
      {
        id: "inworld",
        name: "Inworld",
        description: "面向 AI 角色与互动体验的平台，适合参考角色人格、对话状态和语音互动方案。",
        category: "writing",
        group: "叙事",
        url: "https://www.inworld.ai/",
        supported_types: ["AI 角色", "互动叙事", "语音"],
        status: "online",
      },
      {
        id: "charisma",
        name: "Charisma.ai",
        description: "互动角色与分支叙事工具，适合参考角色对话、剧情节点和互动故事结构。",
        category: "writing",
        group: "叙事",
        url: "https://charisma.ai/",
        supported_types: ["互动故事", "角色对话", "分支叙事"],
        status: "online",
      },
      {
        id: "hidden_door",
        name: "Hidden Door",
        description: "AI 叙事游戏与故事体验平台，适合参考用户参与式世界观和角色驱动玩法。",
        category: "writing",
        group: "叙事",
        url: "https://www.hiddendoor.co/",
        supported_types: ["故事游戏", "世界观", "角色体验"],
        status: "online",
      },
      {
        id: "ai_dungeon",
        name: "AI Dungeon",
        description: "经典 AI 文字冒险平台，适合参考开放式叙事、玩家输入响应和冒险文本体验。",
        category: "writing",
        group: "叙事",
        url: "https://aidungeon.com/",
        supported_types: ["文字冒险", "开放叙事", "玩家输入"],
        status: "online",
      },
    ],
  },
];

export async function fetchAigcCategories(): Promise<AigcCategory[]> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(MOCK_DATA);
    }, 120);
  });
}
